# Generated by Django 5.0.4 on 2024-04-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('dessert', 'Десерт'), ('tea', 'Чай'), ('coffee', 'Кофе')], default='coffe', max_length=30),
        ),
    ]
